### ISSUE TITLE
Migrate Documize Data

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/platform-services-documize#10]
### Task

Migrate Documize data from Pathfinder to Silver Cluster

### Definition of Done

- [ ] Migrate data to Dev or Test Env in Silver
- [ ] Test Data against Matching Documize Version from Pathfinder
- [ ] Test Data against Latest Stable Documize Version
- [ ] Migrate the latest data from Pathfinder into Prod Env on Silver Cluster
- [ ] Verify Data in Prod Env
- [ ] Enable Redirect from Pathfinder to Silver Cluster

**Comment by ShellyXueHan** [comment]
done
