### ISSUE TITLE
Request DNS Entries for Documize

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/platform-services-documize#2]
### Task

Request DNS Entries for Documize to point to the Silver Cluster

### Definition of Done
- [x] Request Made
- [x] `docs.developer.gov.bc.ca` points to Silver Cluster
- [x] `dev.docs.developer.gov.bc.ca` points to Silver Cluster
- [x] `test.docs.developer.gov.bc.ca` points to Silver Cluster

**Comment by j-pye** [comment]
@ShellyXueHan has added the DNS entries. (Thank you)
