### ISSUE TITLE
Setup Documize Repository

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/platform-services-documize#4]
### Task

Setup github repository for development

### Definition of Done

- [x] Add Team to Repository
- [x] Set Protected Brnaches
- [ ] Set Code Owners
- [ ] Configure automatic merges (Optional)
- [x] Configure Code Owners and Merge Policies

**Comment by mitovskaol** [comment]
@j-pye  Can you please have a look at the ticket and close if complete. Can you please also include the path to the repo in the closing comment. Thanks!
